title: DS 2002
description: DS 2002 Course Website
baseurl: "/"
theme: just-the-docs


plugins:
  - jekyll-default-layout
url: https://patrickwuva.github.io/dsclass
aux_links:
  dsclass: https://github.com/patrickwuva/dsclass
